# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rpcService_pb2 as rpcService__pb2


class RPCStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RequestVote = channel.unary_unary(
        '/rpcService.RPC/RequestVote',
        request_serializer=rpcService__pb2.requestVoteRequest.SerializeToString,
        response_deserializer=rpcService__pb2.requsetVoteResponse.FromString,
        )
    self.AppendEntries = channel.unary_unary(
        '/rpcService.RPC/AppendEntries',
        request_serializer=rpcService__pb2.appendEntriesRequest.SerializeToString,
        response_deserializer=rpcService__pb2.appendEntriesResponse.FromString,
        )
    self.PutDelRedirect = channel.unary_unary(
        '/rpcService.RPC/PutDelRedirect',
        request_serializer=rpcService__pb2.putDelRedirectRequest.SerializeToString,
        response_deserializer=rpcService__pb2.putDelRedirectResponse.FromString,
        )
    self.GetRedirect = channel.unary_unary(
        '/rpcService.RPC/GetRedirect',
        request_serializer=rpcService__pb2.getRedirectRequest.SerializeToString,
        response_deserializer=rpcService__pb2.getRedirectResponse.FromString,
        )
    self.PutDel = channel.unary_unary(
        '/rpcService.RPC/PutDel',
        request_serializer=rpcService__pb2.putDelRequest.SerializeToString,
        response_deserializer=rpcService__pb2.putDelResponse.FromString,
        )
    self.Get = channel.unary_unary(
        '/rpcService.RPC/Get',
        request_serializer=rpcService__pb2.getRequest.SerializeToString,
        response_deserializer=rpcService__pb2.getResponse.FromString,
        )
    self.Apply = channel.unary_unary(
        '/rpcService.RPC/Apply',
        request_serializer=rpcService__pb2.applyRequest.SerializeToString,
        response_deserializer=rpcService__pb2.applyResponse.FromString,
        )


class RPCServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RequestVote(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AppendEntries(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PutDelRedirect(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRedirect(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PutDel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Apply(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RPCServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RequestVote': grpc.unary_unary_rpc_method_handler(
          servicer.RequestVote,
          request_deserializer=rpcService__pb2.requestVoteRequest.FromString,
          response_serializer=rpcService__pb2.requsetVoteResponse.SerializeToString,
      ),
      'AppendEntries': grpc.unary_unary_rpc_method_handler(
          servicer.AppendEntries,
          request_deserializer=rpcService__pb2.appendEntriesRequest.FromString,
          response_serializer=rpcService__pb2.appendEntriesResponse.SerializeToString,
      ),
      'PutDelRedirect': grpc.unary_unary_rpc_method_handler(
          servicer.PutDelRedirect,
          request_deserializer=rpcService__pb2.putDelRedirectRequest.FromString,
          response_serializer=rpcService__pb2.putDelRedirectResponse.SerializeToString,
      ),
      'GetRedirect': grpc.unary_unary_rpc_method_handler(
          servicer.GetRedirect,
          request_deserializer=rpcService__pb2.getRedirectRequest.FromString,
          response_serializer=rpcService__pb2.getRedirectResponse.SerializeToString,
      ),
      'PutDel': grpc.unary_unary_rpc_method_handler(
          servicer.PutDel,
          request_deserializer=rpcService__pb2.putDelRequest.FromString,
          response_serializer=rpcService__pb2.putDelResponse.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=rpcService__pb2.getRequest.FromString,
          response_serializer=rpcService__pb2.getResponse.SerializeToString,
      ),
      'Apply': grpc.unary_unary_rpc_method_handler(
          servicer.Apply,
          request_deserializer=rpcService__pb2.applyRequest.FromString,
          response_serializer=rpcService__pb2.applyResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rpcService.RPC', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
